REGISTRATION_FIRST_NAME, REGISTRATION_GENDER, REGISTRATION_PHOTO, REGISTRATION_LOCATION, \
    MAIN_MENU, REGISTRATION_LOCATION_CONTINUATION, CHATS, SEND_1ST_MSG, AGE_REGISTRATION, INVITE_REGISTRATION, \
    MENU_PROFILE, EDIT_PROFILE, EDIT_NAME, EDIT_LAST_NAME, EDIT_AGE, EDIT_LOCATION, EDIT_LOCATION_CONTINUATION, \
    EDIT_PHOTO, EDIT_GENDER, EDIT_ABOUT_ME, EDIT_SEARCH, EDIT_HAIR, DELETE_PROFILE, RESTORE_PROFILE, GALLERY_MENU,\
    LANGUAGE_SELECTION = range(26)